name: Destroy Infrastructure

on:
  workflow_dispatch:  # manual trigger only
    inputs:
      confirm:
        description: "Type DESTROY to confirm execution"
        required: true

jobs:
  pulumi-destroy:
    name: Pulumi Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm ci

      # (Optional) Configure AWS Credentials if not using OIDC
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # Pulumi ESC action (if using OIDC)
      - name: Pulumi ESC - Fetch AWS OIDC Credentials
        if: ${{ secrets.AWS_ACCESS_KEY_ID == '' }}
        uses: pulumi/esc-action@v1
        with:
          environment: "Environments / patel / patel_pulumi"

      - name: Run Pulumi Destroy
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: sahil1610patel/myworkshop/dev
          work-dir: ./ppinfra
          cloud-url: https://api.pulumi.com
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # (AWS creds picked up from environment as in deploy workflow)
